/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestXooDBMainFrame.java
 *
 * Created on Mar 3, 2011, 1:54:05 PM
 */

package com.test;

import com.xoodb.connector.XooDBConnector;
import com.xoodb.exception.XooDBSQLException;
import com.xoodb.query.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhanoopbhaskar
 */
public class TestXooDBMainFrame extends javax.swing.JFrame {
    XooDBConnector xooDBConnector = null;
    /** Creates new form TestXooDBMainFrame */
    public TestXooDBMainFrame() throws XooDBSQLException {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("XooDB tester");
        xooDBConnector = new XooDBConnector("127.0.0.1", 9999, "testDatabase", "root", "root");
        xooDBConnector.connectToXooDB();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        rollnoLabel = new javax.swing.JLabel();
        addRollNoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addNameTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        editRollNoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editNameTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        deleteRollNoTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        panel4 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        rollnoLabel.setText("Roll No:");

        addRollNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRollNoTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(rollnoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addNameTextField)
                            .addComponent(addRollNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRollNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollnoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD", panel1);

        jLabel2.setText("Roll No:");

        jLabel3.setText("Name:");

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editRollNoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editRollNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EDIT", panel2);

        jLabel4.setText("Roll No:");

        deleteButton.setText("DEL");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteButton)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteRollNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deleteRollNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DELETE", panel3);

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        displayTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                displayTableMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(displayTable);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DISPLAY", panel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRollNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRollNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRollNoTextFieldActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void displayTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayTableMouseMoved
        reloadTable();
    }//GEN-LAST:event_displayTableMouseMoved

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String rollNo = addRollNoTextField.getText();
        String name = addNameTextField.getText();
        String query = "insert into student values(" + rollNo + "," + name + ")";
        try {
            xooDBConnector.executeUpdate(query);
        } catch (XooDBSQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error!!!", JOptionPane.ERROR_MESSAGE);
        }
        addRollNoTextField.setText("");
        addNameTextField.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String rollNo = editRollNoTextField.getText();
        String name = editNameTextField.getText();
        String query = "update student set name = " + name + " where rollno = " + rollNo + "";
        try {
            xooDBConnector.executeUpdate(query);
        } catch (XooDBSQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error!!!", JOptionPane.ERROR_MESSAGE);
        }
        editRollNoTextField.setText("");
        editNameTextField.setText("");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String rollNo = deleteRollNoTextField.getText();
        String query = "delete from student where rollno = " + rollNo + "";
        try {
            xooDBConnector.executeUpdate(query);
        } catch (XooDBSQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error!!!", JOptionPane.ERROR_MESSAGE);
        }
        deleteRollNoTextField.setText("");
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TestXooDBMainFrame().setVisible(true);
                } catch (XooDBSQLException ex) {
                    Logger.getLogger(TestXooDBMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addNameTextField;
    private javax.swing.JTextField addRollNoTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField deleteRollNoTextField;
    private javax.swing.JTable displayTable;
    private javax.swing.JTextField editNameTextField;
    private javax.swing.JTextField editRollNoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JLabel rollnoLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private void reloadTable() {
        String[] columnNames = {"Roll No", "Name"};
        String[][] tableData = new String[100][10];
        String query = "select * from student";
        ResultSet resultSet = null;
        try {
            resultSet = xooDBConnector.executeQuery(query);
        } catch (XooDBSQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error!!!", JOptionPane.ERROR_MESSAGE);
        }

        int i = 0;

        while(resultSet.next()) {
            tableData[i][0] = resultSet.getString(0);
            tableData[i][1] = resultSet.getString(1);
            i++;
        }

        DefaultTableModel defaultTableModel = new DefaultTableModel(tableData, columnNames);
        displayTable.setModel(defaultTableModel);
        displayTable.updateUI();
    }

}
